// <auto-generated />
namespace joureny.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class v00mobile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v00mobile));
        
        string IMigrationMetadata.Id
        {
            get { return "201903300936434_v0.0.mobile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
