// <auto-generated />
namespace joureny.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class v00chnagePassword : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v00chnagePassword));
        
        string IMigrationMetadata.Id
        {
            get { return "201903300904409_v0.0.chnagePassword"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
